### PR TITLE
Chore: Update DS stories

### PR DESCRIPTION
**Pull request by josenriagu**
## Description

- update stories source

## Checklist

- [ ] I have read the **README** document
- [ ] I have read the **CONTRIBUTING** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] My commit message follows [Conventional Commit Guideline](https://conventionalcommits.org/)

### CODE REVIEW

**Comment by didd** [comment]
image
that story doesn't look okay to me

**Comment by didd** [comment]
image
that doesn't look like NSFW card

**Comment by didd** [comment]
image
The f in follows needs to be capitalized. I've seen similar issues on other story. And also if you check the default story it doesn't have any card. If the last one is intentional I am okay with it.

**Comment by didd** [comment]
I have seen other places where on a button the first letter is written in small case not sure if its intentional.

**Comment by didd** [comment]
The ui of accordion stories looks a bit weird to me.

image

**Comment by josenriagu** [comment]
@didd this PR is focused on fixing the stories source and doc not the individual stories themselves. a couple of these components and stories are redundant and you will agree with me that it doesn't make sense trying to fix up stories for such components. for instance error-card stories, the error card is no longer used anywhere, the error loader component defined its own error card.
we can create a new issue solely focused on cleaning up DS components and updating all stories (variants)

**Comment by didd** [comment]
@josenriagu that works ... I saw the title of the PR as update DS stories that I took a look at each of them and thats why I shared the feedbacks.

**Review by didd — APPROVED** [review]

**Comment by josenriagu** [comment]
@didd it's been a couple of DS stories/docs update, and will continue on a rolling basis, lol, per new or updates to DS components. Moving forward, it is imperative that for such PRs introducing these DS changes, the corresponding stories be updated also before the PR is approved

**Review by quininez — APPROVED** [review]

**Pull request merged**
