### PR TITLE
refactor(sdk): cleanup old apis && adjustments

### PR DESCRIPTION
**Pull request by kenshyx**
- remove unused libs
- remove unused/old apis
- replace composedb stats api with gql based api
- remove hooks that were using old api

### CODE REVIEW

**Comment by kenshyx** [comment]
* **#2198** <a href="https://app.graphite.dev/github/pr/AKASHAorg/akasha-core/2198?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `next`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @kenshyx and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by kenshyx** [comment]
[happynic](https://app.graphite.dev/settings/meme-library?org=AKASHAorg)

**Review by SeverS — DISMISSED** [review]

**Review by kenshyx — COMMENTED** [review]
[ci](https://app.graphite.dev/settings/meme-library?org=AKASHAorg)

**Review by didd — DISMISSED** [review]

**Review by quininez — APPROVED** [review]

**Review by kenshyx — COMMENTED** [review]
My gifs do not appear, unusable
[shit](https://app.graphite.dev/settings/meme-library?org=AKASHAorg)

**Comment by kenshyx** [comment]
### Merge activity

* **Mar 6, 9:17 AM EST**: @kenshyx merged this pull request with [Graphite](https://app.graphite.dev/github/pr/AKASHAorg/akasha-core/2198).

**Pull request merged**
